# Task-4
Reg ID: GO_STP_6970

1) Import the numpy package under the name np and Print thenumpy version and the config

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


2) Create a null vector of size 10

In [2]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Create Simple 1-D array and check type and check data typesin array

In [3]:
c=np.array([1,2,3,4,5])
print(type(c))
print(c.dtype)

<class 'numpy.ndarray'>
int32


4) How to find number of dimensions,bytes per element and bytes of memeory used

In [4]:
#Create Array
p=np.array([100,20,30,125,50])
print("Size of Array: ",p.size)
print("Memory size of One element of array: ",p.itemsize)
print("Total Bytes  Memory used: ",p.size*p.itemsize)

Size of Array:  5
Memory size of One element of array:  4
Total Bytes  Memory used:  20


5) Create a null vector of size 10 but the fifth value which is 1

In [6]:
x=np.zeros(10)
print("Null Vector: ",x)
x[4] =1
print("Updated Array: ",x)

Null Vector:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Array:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6) Create a vector with values ranging from 10 to 49

In [8]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7) Reverse a vector (first element becomes last)

In [9]:
print("Orignal Array: ",v)
v=v[::-1]
print("Reverse Array: ",v)

Orignal Array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reverse Array:  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8) Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9) Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
nums = np.array([1,2,0,0,4,0])
print("Orignal Array: ",nums)
result=np.where(nums != 0)[0]
print("Indices with non-zero elements are : ",result)

Orignal Array:  [1 2 0 0 4 0]
Indices with non-zero elements are :  [0 1 4]


10) Create a 3x3 identity matrix

In [13]:
id_matrix = np.eye(3)
print("3x3 Matrix: ")
print(id_matrix)

3x3 Matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11) Create a 3x3 identity matrix

In [15]:
x = np.random.random((3,3,3))
print(x)

[[[0.48313579 0.15311003 0.39614674]
  [0.52533757 0.78413286 0.56641936]
  [0.55472223 0.41078363 0.45287479]]

 [[0.44187468 0.21001305 0.86227007]
  [0.52523256 0.99550921 0.62949078]
  [0.20672121 0.78009292 0.29914648]]

 [[0.26109659 0.95687704 0.24836808]
  [0.74336468 0.2825623  0.82284204]
  [0.68718767 0.6850868  0.7731873 ]]]


12) Create a 10x10 array with random values and  find the minimum and maximum.

In [16]:
x= np.random.random((10,10))
print("Min Value: ",x.min())
print(x)
print("Max Value: ",x.max())

Min Value:  0.0008228664615106407
[[7.09800584e-01 7.35868038e-01 2.24794859e-01 2.59395390e-01
  3.21320204e-01 3.11596512e-01 8.25310744e-01 7.10882152e-01
  8.22866462e-04 4.33699994e-03]
 [4.60087110e-01 4.28048637e-01 1.87621830e-01 2.32396827e-01
  1.48981717e-01 2.98996157e-01 5.42950735e-01 9.87429667e-01
  5.90633583e-01 5.80544620e-01]
 [2.84239247e-02 8.39963185e-01 3.22069709e-01 2.27469537e-01
  6.40190850e-01 7.41037902e-01 8.84857526e-01 1.21211996e-01
  3.58755837e-01 2.06240244e-01]
 [2.26521706e-01 7.92826641e-01 7.85892672e-01 9.83998452e-01
  3.24062992e-01 2.70321445e-01 3.78327730e-01 3.18323039e-01
  8.44432118e-01 3.32776542e-01]
 [6.85423900e-01 3.51246082e-01 6.01838921e-02 1.82621175e-01
  8.14925772e-02 4.21571411e-01 8.88381967e-01 1.48910761e-01
  7.05043158e-01 2.87236506e-01]
 [8.40664472e-01 1.86864292e-01 6.91282665e-01 9.49075874e-01
  6.64171601e-01 1.16075092e-01 7.37009397e-01 7.33952862e-01
  7.96737406e-01 3.46806801e-02]
 [5.60608737e-01 9.75598

13) Create a random vector of size 30 and  find the mean value

In [17]:
x=np.random.random((30))
print(x)
print("Mean Value :",np.mean(x))

[2.65541797e-01 7.59335401e-01 7.02742605e-01 9.70990157e-01
 9.41544575e-02 5.51837312e-01 5.32545907e-01 6.50754601e-01
 5.51102622e-01 9.82514690e-01 8.59097216e-01 1.51956036e-04
 2.50226161e-01 2.35558874e-01 6.16611160e-01 2.62708927e-01
 7.51054285e-01 6.15247309e-01 8.80783263e-01 8.63056626e-01
 5.44903735e-01 1.43080476e-01 7.09975047e-01 2.68275460e-01
 7.81590555e-02 6.63779621e-01 8.98058791e-01 6.82075936e-01
 3.53619235e-01 9.81215620e-01]
Mean Value : 0.5573052767571436


14) Create a 2d array with 1 on the border and 0 inside

In [20]:
bor = np.ones((8,8))
bor[1:-1,1:-1]=0
print(bor)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


15) How to add a border (filled with 0's) around an exiting array?

In [22]:
x = np.ones((3,3))
print(x)
x=np.pad(x,pad_width=1, mode='constant', constant_values=0)
print("After Addign 0's Border: ")
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After Addign 0's Border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16) How to Accessing/Changing specific elements rows, colomns,etc in numpy array?
Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

In [24]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
arr[1,5]

13

In [26]:
arr[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
arr[:,2]

array([ 3, 10])

In [28]:
arr[0,:][1:6:2]

array([2, 4, 6])

In [29]:
arr[1,5]= 20
print(arr)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17) How to Convert a 1D array to a 2D array with 2 rows

In [30]:
x = np.array([1,2,3,4,5,6])
print("1D array: ",x)
newx= x.reshape(2,3)
print("2D array: ")
print(newx)

1D array:  [1 2 3 4 5 6]
2D array: 
[[1 2 3]
 [4 5 6]]


18) Create the following pattern without hardcoding. Use onlynumpy functions and the below input array a.

Input:a = np.array([1,2,3])`
    
Desired Output:
    array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [32]:
a=np.array([1,2,3])
ar =np.r_[np.repeat(a,3), np.tile(a,3)]
ar

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

19) Write a program to show how Numpy taking less memorycompared to Python List?

In [33]:
#importing system module
import sys
S = range(1000)
print("Size of Each element of list in bytes: ",sys.getsizeof(S))
print("Size of Whole list in Bytes: ", sys.getsizeof(S)*len(S))
print("Python List size")
# Declaring numpy
D=np.arange(1000)
print("Size of Each element of Numpy array in bytes: ",D.itemsize)
print("Size of Whole Numpy array in Bytes: ",D.size*D.itemsize)

Size of Each element of list in bytes:  48
Size of Whole list in Bytes:  48000
Python List size
Size of Each element of Numpy array in bytes:  4
Size of Whole Numpy array in Bytes:  4000


20) Write a program to show how Numpy taking less timecompared to Python List?

In [36]:
import time
size = 100000
list1 = range(size)
#Declare List
list2 = range(size)
#Declare Array
arr1 = np.arange(size)
arr2 = np.arange(size)
# capture time before python list multiplication
initialTime = time.time()
resultList = [(a,b) for a,b in zip(list1,list2)]
#Calculate Execution Time
print("Time taken by Python List for Multiplication: ",(time.time() - initialTime), "seconds")
# capture time before numpy array multiplication
initialTime = time.time()
resultArray = arr1*arr2
#Calculate Execution Time
print("Time taken by Numpy Array for Multiplication: ",(time.time() - initialTime), "seconds")

Time taken by Python List for Multiplication:  0.09960508346557617 seconds
Time taken by Numpy Array for Multiplication:  0.00800013542175293 seconds
